server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/GuillermoRM03/microservicios-prueba
          search-paths: config-data
  application:
    name: config-service